# Generated by Django 2.0.3 on 2018-03-14 09:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feature_request_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature_Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('client_priority', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('target_date', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feature_request_app.Client')),
                ('product_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feature_request_app.Product_Area')),
            ],
        ),
    ]
