# Generated by Django 2.0.3 on 2018-03-17 18:31

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('feature_request_app', '0005_auto_20180314_1011'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feature_Requests',
            new_name='FeatureRequests',
        ),
        migrations.RenameModel(
            old_name='Product_Area',
            new_name='ProductArea',
        ),
    ]
